name: Gh-Pages

on:
  push:
    branches: [ season2025 ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
      - uses: TesteurManiak/flutter-gh-pages@feat/wasm-compilation
        with:
          baseHref: /FRC_ScoutingDataCollection/
          compileToWasm: true
